"""yt-dlp-oneoff.conf — format overlay layered after yt-dlp.conf for Single download only."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .yt_dlp_presets import FMT_AUDIO, FMT_BEST, FMT_LOW, FMT_MERGE, PRESET_META

ONEOFF_CONF_FILENAME = "yt-dlp-oneoff.conf"

OPTION_LONG = re.compile(r"^\s*--([\w-]+)(?:\s+(.*))?\s*$")

ONEOFF_PRESET_META: list[dict[str, str]] = [
    {
        "id": "balanced",
        "label": "Balanced (merge + audio)",
        "description": "Default for single downloads — merged mkv with audio.",
    },
    {
        "id": "best_quality",
        "label": "Best quality",
        "description": "Stronger format chain for one-off grabs.",
    },
    {
        "id": "fast_low_bw",
        "label": "Fast / low bandwidth",
        "description": "720p-cap merge-friendly chain.",
    },
    {
        "id": "audio_only",
        "label": "Audio only",
        "description": "bestaudio chain.",
    },
    {
        "id": "user_preferences",
        "label": "User preferences",
        "description": "Snapshot captured from disk (Recapture to refresh).",
    },
]

ONEOFF_PRESET_OVERLAYS: dict[str, dict[str, Any]] = {
    "balanced": {
        "format": FMT_MERGE,
        "merge_output_format": "mkv",
        "noplaylist": True,
    },
    "best_quality": {
        "format": FMT_BEST,
        "merge_output_format": "mkv",
        "noplaylist": True,
    },
    "fast_low_bw": {
        "format": FMT_LOW,
        "merge_output_format": "mkv",
        "noplaylist": True,
    },
    "audio_only": {
        "format": FMT_AUDIO,
        "merge_output_format": "mkv",
        "noplaylist": True,
    },
}


def default_oneoff_model() -> dict[str, Any]:
    return dict(ONEOFF_PRESET_OVERLAYS["balanced"])


def merged_oneoff_preset(preset_id: str) -> dict[str, Any]:
    if preset_id == "user_preferences":
        raise ValueError("user_preferences requires snapshot")
    ov = ONEOFF_PRESET_OVERLAYS.get(preset_id)
    if ov is None:
        raise ValueError(f"unknown preset: {preset_id}")
    return dict(ov)


def parse_oneoff_conf(text: str) -> tuple[dict[str, Any], str]:
    """Parse overlay file; return (managed fields, preserved_tail)."""
    managed: dict[str, Any] = {}
    preserved: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            preserved.append(line)
            continue
        m = OPTION_LONG.match(line)
        if not m:
            preserved.append(line)
            continue
        opt, rest = (m.group(1), (m.group(2) or "").strip())
        if rest.startswith('"') and rest.endswith('"'):
            rest = rest[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        if opt == "format":
            managed["format"] = rest
        elif opt == "merge-output-format":
            managed["merge_output_format"] = rest
        elif opt in ("no-playlist", "noplaylist"):
            managed["noplaylist"] = True
        else:
            preserved.append(line)
    return managed, "\n".join(preserved).strip()


def serialize_oneoff_conf(
    model: dict[str, Any],
    *,
    preset_id: str,
    human_note: str = "",
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        f"# Generated by Archive Console — last saved {now} — preset: {preset_id}",
        "# Single-download overlay (read after yt-dlp.conf). Monthly batch jobs use yt-dlp.conf only.",
    ]
    if human_note.strip():
        lines.append("# " + human_note.strip().replace("\n", "\n# "))
    lines.extend(["",])
    fmt = (model.get("format") or "").strip()
    if fmt:
        lines.append(f"--format {fmt}")
    merge = (model.get("merge_output_format") or "").strip()
    if merge:
        lines.append(f"--merge-output-format {merge}")
    if model.get("noplaylist"):
        lines.append("--no-playlist")
    body = "\n".join(lines).rstrip() + "\n"
    return body


def extract_oneoff_banner_preset(text: str) -> str | None:
    for line in text.splitlines():
        m = re.search(r"preset:\s*(\S+)", line)
        if m:
            return m.group(1)
    return None


def ensure_oneoff_conf(archive_root: Path) -> Path:
    """Create yt-dlp-oneoff.conf with balanced defaults when missing."""
    p = archive_root / ONEOFF_CONF_FILENAME
    if p.is_file():
        return p
    p.write_text(
        serialize_oneoff_conf(default_oneoff_model(), preset_id="balanced"),
        encoding="utf-8",
        newline="\n",
    )
    return p


def oneoff_conf_cli_preview(model: dict[str, Any]) -> str:
    chunks = [
        "yt-dlp",
        "--config-locations",
        ONEOFF_CONF_FILENAME,
        "--config-locations",
        "yt-dlp.conf",
    ]
    fmt = (model.get("format") or "").strip()
    if fmt:
        chunks.extend(["--format", fmt])
    merge = (model.get("merge_output_format") or "").strip()
    if merge:
        chunks.extend(["--merge-output-format", merge])
    if model.get("noplaylist"):
        chunks.append("--no-playlist")
    return " ".join(chunks)


def apply_oneoff_builtin_preset(current: dict[str, Any], preset_id: str) -> dict[str, Any]:
    merged = merged_oneoff_preset(preset_id)
    out = dict(current)
    out.update(merged)
    return out
